
// console.log(number1);//undefined
// console.log(number2);//
// console.log(number3);//







 var number1=3;
let number2=2.9;
 
const number3=0xff;

var firstName="Aliy";
var middleName='Emad';
var lastName=`AboShoSha`;
var numbers=[1,"a",3,4,5];
console.log(typeof numbers);
var flag=true;

console.log(numbers);
var summationArray1=numbers+flag;
console.log(summationArray1);
console.log(numbers+flag);
console.log(numbers+number1);
console.log(numbers+firstName);
console.log("This is the External JavaScript file");

// var name1= firstName[3]
// console.log(name1);
// name1="A";
// firstName[3]=name1;
// console.log(name1);
// console.log(firstName);


console.log(typeof(number1));
console.log(typeof(number2));
console.log(typeof(number3));
console.log(typeof(firstName));
console.log(typeof(middleName));
console.log(typeof(lastName));





